name: Renovatebot auto-merge

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  renovatebot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: pnpm
    - name: Build checking
      run: |
        pnpm install --frozen-lockfile
        pnpmx dlx @cloudflare/next-on-pages
    - name: Enable auto-merge for Dependabot PRs
      if: github.event_name != 'pull_request' && github.actor == 'renovate[bot]'
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
